version: 0.1
phases:
  pre-build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean prepare-package war:explode
  post-build:
    commands:
      - echo "Entered post-build phase"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*


